module.exports = {
  NEW_TASK: 'NEW_TASK',
  NEW_EVALUATION: 'NEW_EVALUATION',
  EVALUATION_REJECTED_BY_CUSTOMER: 'EVALUATION_REJECTED_BY_CUSTOMER',
  EVALUATION_ACCEPTED_BY_CUSTOMER: 'EVALUATION_ACCEPTED_BY_CUSTOMER',
  EVALUATION_ACCEPTED_BY_WORKER: 'EVALUATION_ACCEPTED_BY_WORKER',
  TASK_RATEABLE: 'TASK_RATEABLE',
};
